DROP DATABASE IF EXISTS content;
CREATE DATABASE content;
USE content;

DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(30) NOT NULL,
  points INTEGER UNSIGNED NOT NULL DEFAULT 0,
  lastUsageDate DATE,
  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS items;
CREATE TABLE items (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(30) NOT NULL,
  lastUserId INTEGER UNSIGNED,
  lastUsageDate DATE,
  intervalDays INTEGER UNSIGNED NOT NULL,
  FOREIGN KEY (lastUserId) REFERENCES users(id),
  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

INSERT INTO items(name, intervalDays) VALUES
("kitchen", 7),
("bathroom", 7);