// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/franpog859/cleanaux-backend/content-service/internal/model"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *Client) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllItems provides a mock function with given fields:
func (_m *Client) GetAllItems() ([]model.Item, error) {
	ret := _m.Called()

	var r0 []model.Item
	if rf, ok := ret.Get(0).(func() []model.Item); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Item)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateItem provides a mock function with given fields: updateItem
func (_m *Client) UpdateItem(updateItem model.UpdateItem) error {
	ret := _m.Called(updateItem)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.UpdateItem) error); ok {
		r0 = rf(updateItem)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
