DROP DATABASE IF EXISTS content;
CREATE DATABASE content;
USE content;

DROP TABLE IF EXISTS items;
CREATE TABLE items (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  lastUsageDate DATE NOT NULL,
  intervalDays INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
