// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/franpog859/cleanaux-backend/auth-service/internal/model"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// GetAuthorizedUsers provides a mock function with given fields: _a0, _a1
func (_m *Client) GetAuthorizedUsers(_a0 string, _a1 string) ([]model.User, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []model.User
	if rf, ok := ret.Get(0).(func(string, string) []model.User); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
