apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: content-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: content-service
    spec:
      containers:
      - name: content-service
        image: franpog859/content-service:v0.5.11
        ports:
        - containerPort: 8000
