apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      initContainers:
      - name: init-script-downloader
        image: appropriate/curl
        args:
        - "-o"
        - "/tmp/data/db-init.sql"
        - "https://raw.githubusercontent.com/franpog859/cleanaux-backend/master/content-service/init/db-init.sql"
        volumeMounts:
        - name: init-script
          mountPath: /tmp/data
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: init-script
        persistentVolumeClaim:
          claimName: init-script
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim

