apiVersion: v1
kind: Service
metadata:
  name: content-service-external
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: content-service