kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: mysql-pv
  capacity:
    storage: 0.5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: mysql-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-init-pv-volume
  labels:
    type: local
spec:
  storageClassName: mysql-init-pv
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-init-script
spec:
  storageClassName: mysql-init-pv
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Mi
