apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  template: 
    metadata:
      labels: 
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: franpog859/auth-service:v0.2
        ports:
        - containerPort: 8000