apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  template: 
    metadata:
      labels: 
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: franpog859/auth-service:v0.6.0
        ports:
        - containerPort: 8000
        - containerPort: 8001
        volumeMounts:
        - name: jwt-secret
          mountPath: "/data/secret"
          readOnly: true
      volumes:
      - name: jwt-secret
        secret:
          secretName: jwt-secret
