apiVersion: v1
kind: Service
metadata:
  name: auth-service-external
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: auth-service
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-internal
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8001
    protocol: TCP
  selector:
    app: auth-service