apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: entry-service
spec:
  replicas: 2
  template: 
    metadata:
      labels: 
        app: entry-service
    spec:
      containers:
      - name: entry-service
        image: franpog859/entry-service:0.1
        ports:
        - containerPort: 8000